//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBPInventoryNetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permit
    {
        public int Id { get; set; }
        public int GoupId { get; set; }
        public string Modify { get; set; }
        public string Edit { get; set; }
        public string Deletee { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Catalog Catalog { get; set; }
    }
}
