//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBPInventoryNetApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public int Id { get; set; }
        public string TaxTag { get; set; }
        public decimal Perecentage { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public bool Status { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
